/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRegistreIndexRouteImport } from './routes/_authenticated/registre.index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiRegistreTemperatureRouteImport } from './routes/api.registre.temperature'
import { Route as ApiRegistrePhRouteImport } from './routes/api.registre.ph'
import { Route as AuthenticatedRegistreTemperatureRouteImport } from './routes/_authenticated/registre.temperature'
import { Route as AuthenticatedRegistrePhRouteImport } from './routes/_authenticated/registre.ph'

const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistreIndexRoute =
  AuthenticatedRegistreIndexRouteImport.update({
    id: '/registre/',
    path: '/registre/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistreTemperatureRoute = ApiRegistreTemperatureRouteImport.update({
  id: '/api/registre/temperature',
  path: '/api/registre/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrePhRoute = ApiRegistrePhRouteImport.update({
  id: '/api/registre/ph',
  path: '/api/registre/ph',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistreTemperatureRoute =
  AuthenticatedRegistreTemperatureRouteImport.update({
    id: '/registre/temperature',
    path: '/registre/temperature',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistrePhRoute = AuthenticatedRegistrePhRouteImport.update({
  id: '/registre/ph',
  path: '/registre/ph',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/registre/ph': typeof AuthenticatedRegistrePhRoute
  '/registre/temperature': typeof AuthenticatedRegistreTemperatureRoute
  '/api/registre/ph': typeof ApiRegistrePhRoute
  '/api/registre/temperature': typeof ApiRegistreTemperatureRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/registre/': typeof AuthenticatedRegistreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/registre/ph': typeof AuthenticatedRegistrePhRoute
  '/registre/temperature': typeof AuthenticatedRegistreTemperatureRoute
  '/api/registre/ph': typeof ApiRegistrePhRoute
  '/api/registre/temperature': typeof ApiRegistreTemperatureRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/registre': typeof AuthenticatedRegistreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/_authenticated/registre/ph': typeof AuthenticatedRegistrePhRoute
  '/_authenticated/registre/temperature': typeof AuthenticatedRegistreTemperatureRoute
  '/api/registre/ph': typeof ApiRegistrePhRoute
  '/api/registre/temperature': typeof ApiRegistreTemperatureRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/registre/': typeof AuthenticatedRegistreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset'
    | '/registre/ph'
    | '/registre/temperature'
    | '/api/registre/ph'
    | '/api/registre/temperature'
    | '/api/trpc/$'
    | '/registre/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset'
    | '/registre/ph'
    | '/registre/temperature'
    | '/api/registre/ph'
    | '/api/registre/temperature'
    | '/api/trpc/$'
    | '/registre'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset'
    | '/_authenticated/registre/ph'
    | '/_authenticated/registre/temperature'
    | '/api/registre/ph'
    | '/api/registre/temperature'
    | '/api/trpc/$'
    | '/_authenticated/registre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetRoute: typeof ResetRoute
  ApiRegistrePhRoute: typeof ApiRegistrePhRoute
  ApiRegistreTemperatureRoute: typeof ApiRegistreTemperatureRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registre/': {
      id: '/_authenticated/registre/'
      path: '/registre'
      fullPath: '/registre/'
      preLoaderRoute: typeof AuthenticatedRegistreIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registre/temperature': {
      id: '/api/registre/temperature'
      path: '/api/registre/temperature'
      fullPath: '/api/registre/temperature'
      preLoaderRoute: typeof ApiRegistreTemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registre/ph': {
      id: '/api/registre/ph'
      path: '/api/registre/ph'
      fullPath: '/api/registre/ph'
      preLoaderRoute: typeof ApiRegistrePhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registre/temperature': {
      id: '/_authenticated/registre/temperature'
      path: '/registre/temperature'
      fullPath: '/registre/temperature'
      preLoaderRoute: typeof AuthenticatedRegistreTemperatureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registre/ph': {
      id: '/_authenticated/registre/ph'
      path: '/registre/ph'
      fullPath: '/registre/ph'
      preLoaderRoute: typeof AuthenticatedRegistrePhRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedRegistrePhRoute: typeof AuthenticatedRegistrePhRoute
  AuthenticatedRegistreTemperatureRoute: typeof AuthenticatedRegistreTemperatureRoute
  AuthenticatedRegistreIndexRoute: typeof AuthenticatedRegistreIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRegistrePhRoute: AuthenticatedRegistrePhRoute,
  AuthenticatedRegistreTemperatureRoute: AuthenticatedRegistreTemperatureRoute,
  AuthenticatedRegistreIndexRoute: AuthenticatedRegistreIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetRoute: ResetRoute,
  ApiRegistrePhRoute: ApiRegistrePhRoute,
  ApiRegistreTemperatureRoute: ApiRegistreTemperatureRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
